# Generated by Django 3.1.2 on 2020-10-18 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('semister', models.CharField(max_length=10)),
                ('dept', models.CharField(choices=[('IIT', 'IIT'), ('CSE', 'CSE'), ('Mathmatics', 'Mathmatics'), ('Statistics', 'Statistics')], max_length=100)),
                ('batch', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('is_student', models.BooleanField(default=False)),
                ('is_attendence', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
