# Generated by Django 3.1.2 on 2020-10-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0003_semister'),
    ]

    operations = [
        migrations.AddField(
            model_name='semister',
            name='have_attendence',
            field=models.BooleanField(default=False),
        ),
    ]
