# Generated by Django 3.1.2 on 2020-10-18 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0004_semister_have_attendence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semister_Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semister', models.CharField(max_length=10)),
                ('admission_fee', models.FloatField(null=True)),
                ('session_charge', models.FloatField(null=True)),
                ('exam_fee', models.FloatField(null=True)),
                ('hall_fee', models.FloatField(null=True)),
                ('library_fee', models.FloatField(null=True)),
                ('transport_fee', models.FloatField(null=True)),
                ('medical_fee', models.FloatField(null=True)),
                ('bank_sleep', models.BooleanField(default=True)),
                ('is_hall_verify', models.BooleanField(default=False)),
                ('is_register_verify', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final.student')),
            ],
        ),
    ]
