# Generated by Django 3.1.2 on 2020-10-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0005_semister_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('profession_id', models.CharField(blank=True, max_length=100, null=True)),
                ('Role', models.CharField(blank=True, choices=[('Teacher', 'Teacher'), ('Hall Staff', 'Hall Staff'), ('Register', 'Register')], max_length=100, null=True)),
                ('department', models.CharField(blank=True, choices=[('IIT', 'IIT'), ('CSE', 'CSE'), ('LAW', 'LAW')], max_length=100, null=True)),
                ('is_approved_by_register', models.BooleanField(default=True)),
            ],
        ),
    ]
