# Generated by Django 3.1.2 on 2020-10-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0006_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='Role',
            field=models.CharField(blank=True, choices=[('Teacher', 'Teacher'), ('Register', 'Register')], max_length=100, null=True),
        ),
    ]
