# Generated by Django 3.1.2 on 2020-10-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_approved_by_register',
            field=models.BooleanField(default=False),
        ),
    ]
