# Generated by Django 3.1.2 on 2020-10-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_is_approved_by_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(blank=True, choices=[('IIT', 'IIT'), ('CSE', 'CSE'), ('LAW', 'LAW')], max_length=100, null=True),
        ),
    ]
