# Generated by Django 3.1.2 on 2020-10-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20201011_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='is_approved_by_register',
            field=models.BooleanField(default=True),
        ),
    ]
