# Generated by Django 3.1.2 on 2020-10-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('dept', models.CharField(blank=True, choices=[('IIT', 'IIT'), ('CSE', 'CSE'), ('Mathmatics', 'Mathmatics'), ('Statistics', 'Statistics')], max_length=100, null=True)),
                ('batch', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
