# Generated by Django 3.1.2 on 2020-10-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_attendence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='semister',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
