# Generated by Django 3.1.2 on 2020-10-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_fee',
            old_name='is_money_approved',
            new_name='is_hall_verify',
        ),
        migrations.AddField(
            model_name='student_fee',
            name='is_register_verify',
            field=models.BooleanField(default=False),
        ),
    ]
